In [1]:
print("Fake news detection process started")

Fake news detection process started

In [2]:
import pandas as pd

In [6]:
fake_data = pd.read_csv("../data/Fake.csv")

In [4]:
fake_data.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [3]:
true_data = pd.read_csv("../data/True.csv")

In [4]:
true_data.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [7]:
fake_data["label"] = 0
true_data["label"] = 1

In [8]:
fake_data.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [9]:
true_data.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [10]:
data= pd.concat([fake_data, true_data])

In [11]:
data.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [12]:
data.shape

(44898, 5)

In [21]:
data = data.sample(frac=1)

In [23]:
data=data.reset_index(drop=True)

In [24]:
data.head()

,level_0,index,title,text,subject,date,label
0,14876,1016,Top Republican senator testifies for Menendez ...,(Reuters) - Republican U.S. Senator Lindsay Gr...,politicsNews,"October 26, 2017",1
1,27496,4304,Trump says tax reform 'will be better' if Obam...,WASHINGTON (Reuters) - President Donald Trump ...,politicsNews,"April 11, 2017",1
2,22959,15392,[VIDEO] HERO WHO EXPOSED PLANNED PARENTHOOD SA...,David Daleiden: We probably have hundreds to ...,politics,"Jul 30, 2015",0
3,16898,5310,Deportation spat overshadows Trump envoys' tal...,MEXICO CITY (Reuters) - A bid by U.S. Presiden...,politicsNews,"February 23, 2017",1
4,15227,13689,Ireland set for election if Deputy PM does not...,DUBLIN (Reuters) - Ireland s Deputy Prime Mini...,worldnews,"November 27, 2017",1

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
vectorizer = TfidfVectorizer()

In [50]:
x= vectorizer.fit_transform(data["text"])

In [29]:
y= data["label"]

In [30]:
x.shape

(44898, 122002)

In [31]:
from sklearn.model_selection import train_test_split

In [33]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [34]:
x_train.shape

(35918, 122002)

In [35]:
x_test.shape

(8980, 122002)

In [36]:
from sklearn.linear_model import LogisticRegression

In [37]:
model= LogisticRegression()

In [38]:
model.fit(x_train, y_train)

LogisticRegression()

In [39]:
predictions = model.predict(x_test)

In [40]:
predictions[:10]

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [42]:
from sklearn.metrics import accuracy_score

In [43]:
accuracy = accuracy_score(y_test, predictions)

In [44]:
print("Accuracy:",accuracy)

Accuracy: 0.9851893095768374

In [45]:
print("Accuracy Percentage:",accuracy*100)

Accuracy Percentage: 98.51893095768374

In [51]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]','',text)
    return text

In [52]:
news= "Government announces new education policy"

In [53]:
clean_news = clean_text(news)

In [54]:
news_vector = vectorizer.transform([clean_news])

In [55]:
prediction = model.predict(news_vector)

In [56]:
print(prediction)

[0]

In [60]:
if prediction[0] == 0:
    print("Fake News")
else:
    print("Real News")

Fake News

In [61]:
import pickle

In [62]:
with open("../model/fake_news_model.pkl","wb") as file:
    pickle.dump(model, file)

In [63]:
with open("../model/vectorizer.pkl","wb") as file:
    pickle.dump(vectorizer, file)